"use client";
import {Product,price_lists} from '@/types';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {StatusBadge} from '@/components/workspace/primitives';
import {formatCurrency,formatDate} from '@/lib/utils';
import {Edit,History} from 'lucide-react';
import {productDescriptionDetail} from '@/lib/product-description';
export function ProductDetailSheet({product,priceLists,open,onOpenChange,onEdit,onHistory,canEdit}:{product:Product|null;priceLists:price_lists[];open:boolean;onOpenChange:(open:boolean)=>void;onEdit:()=>void;onHistory:()=>void;canEdit:boolean}){if(!product)return null;const description=productDescriptionDetail(product.name,product.description);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="left-auto right-0 top-0 h-dvh max-h-dvh w-full max-w-xl translate-x-0 translate-y-0 rounded-none content-start gap-6 sm:p-7"><DialogHeader><p className="eyebrow">Product details</p><DialogTitle className="text-lg leading-7">{product.name}</DialogTitle><DialogDescription>{product.sku}{product.model_number?' · '+product.model_number:''}</DialogDescription></DialogHeader><div className="flex flex-wrap items-center gap-2"><StatusBadge status={product.is_active?'active':'archived'}/><span className="rounded-md border px-2 py-1 text-xs text-muted-foreground">{product.category?.name||'Uncategorized'}</span></div><div className="flex flex-wrap gap-2 border-b border-slate-200 pb-6">{canEdit&&<Button variant="outline" onClick={onEdit}><Edit/>Edit product</Button>}<Button variant="outline" onClick={onHistory}><History/>Price history</Button></div><section className="form-section"><h3 className="form-section-title">Description</h3><p className="whitespace-pre-wrap break-words text-[13px] leading-6 text-slate-600">{description||'No additional description supplied.'}</p>{product.specifications&&<><h3 className="form-section-title">Specifications</h3><p className="whitespace-pre-wrap break-words text-[13px] leading-6 text-slate-600">{product.specifications}</p></>}</section><section className="space-y-3"><h3 className="form-section-title">Master prices</h3><div className="divide-y divide-slate-200 rounded-lg border border-slate-200">{priceLists.filter(l=>l.is_active).map(l=>{const p=product.prices?.find(p=>p.price_list_id===l.id);return <div key={l.id} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-medium">{l.name}</p><p className="mt-1 text-xs text-muted-foreground">{p?'Updated '+formatDate(p.updated_at):l.currency}</p></div><p className="text-sm font-semibold tabular-nums">{p?formatCurrency(p.unit_price,l.currency):'Not priced'}</p></div>;})}</div></section><dl className="grid grid-cols-2 gap-4 border-t pt-5 text-xs"><div><dt className="text-muted-foreground">HSN code</dt><dd className="mt-1 font-medium">{product.hsn_code||'Not supplied'}</dd></div><div><dt className="text-muted-foreground">Last updated</dt><dd className="mt-1 font-medium">{formatDate(product.updated_at)}</dd></div></dl></DialogContent></Dialog>;}
