"use client";
import React from 'react';
import { Plus,ChevronsUpDown,Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { SearchInput,EmptyState,SectionHeader } from '@/components/workspace/primitives';
import { Customer } from '@/types';
import { QuickCustomerDialog } from '@/components/customers/quick-customer-dialog';
export function CustomerSection({customers,selectedCustomerId,onSelectCustomer,onCustomerCreated}:{customers:Customer[];selectedCustomerId:string;onSelectCustomer:(c:Customer)=>void;onCustomerCreated:(c:Customer)=>void}){
 const [open,setOpen]=React.useState(false);const [adding,setAdding]=React.useState(false);const [query,setQuery]=React.useState('');const [active,setActive]=React.useState(0);const selected=customers.find(c=>c.id===selectedCustomerId);const listId=React.useId();
 const rows=customers.filter(c=>`${c.name} ${c.contact_person||''} ${c.country||''} ${c.email||''}`.toLowerCase().includes(query.toLowerCase())).slice(0,30);
 React.useEffect(()=>{if(open)document.getElementById(listId+'-'+active)?.scrollIntoView({block:'nearest'});},[open,active,query,listId]);
 const choose=(c:Customer)=>{onSelectCustomer(c);setOpen(false);};
 return <section className="surface p-4 space-y-3 min-w-0"><SectionHeader title="Customer" actions={<Button size="sm" variant="ghost" onClick={()=>setAdding(true)}><Plus className="mr-1 h-3.5 w-3.5"/>New</Button>}/><Button variant="outline" role="combobox" aria-expanded={open} aria-label="Select Customer" aria-haspopup="dialog" className="w-full justify-between font-normal" onClick={()=>{setQuery('');setActive(0);setOpen(true);}}><span className="truncate">{selected?.name||'Choose a customer…'}</span><ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 text-muted-foreground"/></Button><p className="rounded-md border border-dashed bg-slate-50/60 px-3 py-3 text-xs leading-6 text-muted-foreground min-h-4 break-words">{selected?[selected.contact_person,selected.country,selected.email].filter(Boolean).join(' · '):'Search existing customers or add one without leaving this quotation.'}</p>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Select Customer</DialogTitle><DialogDescription>Search by company, contact, country, or email.</DialogDescription></DialogHeader><SearchInput value={query} onValueChange={v=>{setQuery(v);setActive(0);}} placeholder="Search customers…" role="combobox" aria-expanded aria-controls={listId} aria-activedescendant={rows[active]?`${listId}-${active}`:undefined} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(n=>Math.min(n+1,Math.max(0,rows.length-1)));}if(e.key==='ArrowUp'){e.preventDefault();setActive(n=>Math.max(0,n-1));}if(e.key==='Enter'&&rows[active]){e.preventDefault();choose(rows[active]);}}}/><div id={listId} role="listbox" aria-label="Customer results" className="max-h-80 overflow-auto space-y-1">{rows.map((c,i)=><button key={c.id} id={`${listId}-${i}`} role="option" aria-selected={i===active} onMouseEnter={()=>setActive(i)} onClick={()=>choose(c)} className={`w-full rounded-md p-3 text-left flex justify-between gap-3 ${active===i?'bg-muted':'hover:bg-muted/60'}`}><span className="min-w-0"><span className="block font-medium truncate">{c.name}</span><span className="mt-1 block text-xs text-muted-foreground truncate">{[c.contact_person,c.country,c.email].filter(Boolean).join(' · ')}</span></span>{c.id===selectedCustomerId&&<Check className="h-4 w-4 shrink-0 text-primary"/>}</button>)}{!rows.length&&<EmptyState compact title="No customers found" description="Try another search or add a customer."/>}</div><Button variant="outline" onClick={()=>{setOpen(false);setAdding(true);}}><Plus className="mr-2 h-4 w-4"/>Add New Customer</Button></DialogContent></Dialog>
 <QuickCustomerDialog open={adding} onOpenChange={setAdding} onCustomerCreated={onCustomerCreated}/></section>;
}
