"use client";
import React from 'react';
import { Tags } from 'lucide-react';
import { SectionHeader,ConfirmationDialog,InlineError } from '@/components/workspace/primitives';
import { price_lists as PriceList, QuotationType } from '@/types';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { DEFAULT_INR_PER_USD } from '@/lib/quotation-currency';
export function PriceListSection({priceLists,selectedPriceListId,quotationType,quotationCurrency,exchangeRate,onSelectPriceList,onChangePricing,onChangeQuotationType,hasItems}:{priceLists:PriceList[];selectedPriceListId:string;quotationType:QuotationType;quotationCurrency:string;exchangeRate:number;onSelectPriceList:(p:PriceList)=>void|Promise<void>;onChangePricing:(currency:string,rate:number)=>void|Promise<void>;onChangeQuotationType:(quotationType:QuotationType)=>void|Promise<void>;hasItems:boolean}){
 const [pending,setPending]=React.useState<PriceList|null>(null);const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');const [rateInput,setRateInput]=React.useState(String(exchangeRate));const selected=priceLists.find(p=>p.id===selectedPriceListId);const id=React.useId();
 React.useEffect(()=>setRateInput(String(exchangeRate)),[exchangeRate]);
 async function change(p:PriceList){setBusy(true);setError('');try{await onSelectPriceList(p);}catch(e){setError(e instanceof Error?e.message:'Could not refresh prices.');}finally{setBusy(false);}}
 async function changePricing(currency:string,rate:number){setBusy(true);setError('');try{await onChangePricing(currency,rate);}catch(e){setError(e instanceof Error?e.message:'Could not convert quotation prices.');}finally{setBusy(false);}}
 async function changeType(type:QuotationType){setBusy(true);setError('');try{await onChangeQuotationType(type);}catch(e){setError(e instanceof Error?e.message:'Could not change quotation format.');}finally{setBusy(false);}}
 function commitRate(){const rate=Number(rateInput);if(rate>0&&rate<=1000000)void changePricing('USD',rate);else{setRateInput(String(exchangeRate));setError('Enter a valid INR per USD conversion rate.');}}
 const supportsUsd=selected?.currency==='INR';
 return <section className="surface p-4 space-y-3 min-w-0"><SectionHeader title="Pricing context" icon={Tags} actions={selected&&<span className="rounded-md border px-2 py-1 text-xs font-semibold">{quotationCurrency}</span>}/><div className="rounded-lg border bg-muted/20 p-3"><p className="mb-2 text-xs font-medium">Quotation format</p><div className="grid grid-cols-2 gap-2"><Button type="button" size="sm" variant={quotationType==='indian'?'default':'outline'} disabled={busy} onClick={()=>void changeType('indian')}>Indian Quotation</Button><Button type="button" size="sm" variant={quotationType==='export'?'default':'outline'} disabled={busy} onClick={()=>void changeType('export')}>Export Quotation</Button></div><p className="mt-2 text-[11px] leading-4 text-muted-foreground">{quotationType==='export'?'International USD format with export terms, SWIFT bank details, and export closing.':'Domestic format with GST terms and Indian bank details.'}</p></div><label htmlFor={id} className="sr-only">Pricing Schedule</label><select id={id} className="select-control" disabled={busy} value={selectedPriceListId} onChange={e=>{const p=priceLists.find(v=>v.id===e.target.value);if(p&&p.id!==selectedPriceListId){if(hasItems)setPending(p);else void change(p);}}}>{!selected&&<option value="">Choose a price list…</option>}{priceLists.map(p=><option key={p.id} value={p.id} disabled={!p.is_active&&p.id!==selectedPriceListId}>{p.name} ({p.currency}){!p.is_active?' · Archived':''}</option>)}</select>
  {selected&&<div className="rounded-lg border bg-muted/20 p-3"><p className="mb-2 text-xs font-medium">Quotation currency</p><div className="flex flex-wrap items-center gap-2"><Button type="button" size="sm" variant={quotationCurrency===selected.currency?'default':'outline'} disabled={busy||(quotationType==='export'&&selected.currency!=='USD')} title={quotationType==='export'?'Export quotations use USD':''} onClick={()=>void changePricing(selected.currency,1)}>{selected.currency}</Button>{supportsUsd&&<Button type="button" size="sm" variant={quotationCurrency==='USD'?'default':'outline'} disabled={busy} onClick={()=>void changePricing('USD',exchangeRate>1?exchangeRate:DEFAULT_INR_PER_USD)}>USD ($)</Button>}{supportsUsd&&quotationCurrency==='USD'&&<label className="ml-auto flex items-center gap-2 text-xs"><span className="whitespace-nowrap">1 USD =</span><Input aria-label="INR per USD conversion rate" type="number" min="0.000001" max="1000000" step="0.01" value={rateInput} disabled={busy} onChange={event=>setRateInput(event.target.value)} onBlur={commitRate} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();commitRate();}}} className="h-8 w-24 text-right tabular-nums"/><span>INR</span></label>}</div></div>}
  <p className="text-xs text-muted-foreground">{busy?'Refreshing and converting prices…':quotationCurrency==='USD'&&selected?.currency==='INR'?`Master and quoted values use the selected INR list at ${exchangeRate} INR per USD. You can still edit quoted prices separately.`:hasItems?'Changing lists replaces master and quoted prices for all items.':selected?.description||'Current master prices load automatically from this list.'}</p><InlineError message={error}/><ConfirmationDialog open={!!pending} onOpenChange={v=>!v&&setPending(null)} title="Refresh prices from another list?" description={`Switch to ${pending?.name} (${pending?.currency})? All master and quoted prices will reset to this list. Any quoted-price overrides will be replaced. Quantities and discounts stay unchanged.`} confirmLabel="Switch & Refresh Prices" destructive={false} onConfirm={async()=>{if(pending)await change(pending);}}/></section>;
}
