"use client";
import React from 'react';
import { Tags } from 'lucide-react';
import { SectionHeader,ConfirmationDialog,InlineError } from '@/components/workspace/primitives';
import { price_lists as PriceList } from '@/types';
export function PriceListSection({priceLists,selectedPriceListId,onSelectPriceList,hasItems}:{priceLists:PriceList[];selectedPriceListId:string;onSelectPriceList:(p:PriceList)=>void|Promise<void>;hasItems:boolean}){
 const [pending,setPending]=React.useState<PriceList|null>(null);const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');const selected=priceLists.find(p=>p.id===selectedPriceListId);const id=React.useId();
 async function change(p:PriceList){setBusy(true);setError('');try{await onSelectPriceList(p);}catch(e){setError(e instanceof Error?e.message:'Could not refresh prices.');}finally{setBusy(false);}}
 return <section className="surface p-4 space-y-3 min-w-0"><SectionHeader title="Pricing context" icon={Tags} actions={selected&&<span className="rounded-md border px-2 py-1 text-xs font-semibold">{selected.currency}</span>}/><label htmlFor={id} className="sr-only">Pricing Schedule</label><select id={id} className="select-control" disabled={busy} value={selectedPriceListId} onChange={e=>{const p=priceLists.find(v=>v.id===e.target.value);if(p&&p.id!==selectedPriceListId){if(hasItems)setPending(p);else void change(p);}}}>{!selected&&<option value="">Choose a price list…</option>}{priceLists.map(p=><option key={p.id} value={p.id} disabled={!p.is_active&&p.id!==selectedPriceListId}>{p.name} ({p.currency}){!p.is_active?' · Archived':''}</option>)}</select><p className="text-xs text-muted-foreground">{busy?'Refreshing current prices…':hasItems?'Changing lists replaces master and quoted prices for all items.':selected?.description||'Current master prices load automatically from this list.'}</p><InlineError message={error}/><ConfirmationDialog open={!!pending} onOpenChange={v=>!v&&setPending(null)} title="Refresh prices from another list?" description={`Switch to ${pending?.name} (${pending?.currency})? All master and quoted prices will reset to this list. Any quoted-price overrides will be replaced. Quantities and discounts stay unchanged.`} confirmLabel="Switch & Refresh Prices" destructive={false} onConfirm={async()=>{if(pending)await change(pending);}}/></section>;
}
