"use client";
import React from 'react';
import { Plus,MoreHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { PageHeader,SearchInput,InlineError,FormField,StatusBadge,ConfirmationDialog } from '@/components/workspace/primitives';
import { DataTable,DataColumn } from '@/components/workspace/data-table';
import { PriceMatrixModal } from '@/components/products/price-matrix-modal';
import { useAsyncData } from '@/lib/ui-hooks';
import { db } from '@/lib/db';
import { formatCurrency,formatDate } from '@/lib/utils';
import { price_lists as PriceList,Product } from '@/types';
import { toast } from 'sonner';
export default function PriceListsPage(){
 const {data,loading,error,reload}=useAsyncData(async()=>{const [lists,products]=await Promise.all([db.fetchPriceLists(),db.fetchProducts()]);return {lists,products};},{lists:[] as PriceList[],products:[] as Product[]});
 const [query,setQuery]=React.useState('');const [status,setStatus]=React.useState('all');const [open,setOpen]=React.useState(false);const [editing,setEditing]=React.useState<PriceList|null>(null);const [archive,setArchive]=React.useState<PriceList|null>(null);const [details,setDetails]=React.useState<PriceList|null>(null);const [priceProduct,setPriceProduct]=React.useState<Product|null>(null);const [detailQuery,setDetailQuery]=React.useState('');const [form,setForm]=React.useState({name:'',currency:'USD',description:''});const [saving,setSaving]=React.useState(false);const [formError,setFormError]=React.useState('');
 const priced=(id:string)=>data.products.filter(p=>p.prices?.some(price=>price.price_list_id===id));
 const updated=(id:string)=>data.products.flatMap(p=>p.prices||[]).filter(p=>p.price_list_id===id).map(p=>p.updated_at).sort().at(-1)||'';
 function edit(pl:PriceList|null){setEditing(pl);setForm({name:pl?.name||'',currency:pl?.currency||'USD',description:pl?.description||''});setFormError('');setOpen(true);}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setFormError('');try{if(editing)await db.updatePriceList(editing.id,form);else await db.createPriceList(form);await reload();setOpen(false);toast.success(editing?'Price list updated':'Price list created');}catch(e){setFormError(e instanceof Error?e.message:'Could not save price list.');}finally{setSaving(false);}}
 const rows=React.useMemo(()=>data.lists.filter(pl=>(status==='all'||pl.is_active===(status==='active'))&&`${pl.name} ${pl.currency} ${pl.description}`.toLowerCase().includes(query.toLowerCase())),[data,query,status]);
 const columns:DataColumn<PriceList>[]=[{key:'name',label:'Price list',sortValue:p=>p.name,cell:p=><button className="text-left font-medium max-w-xs" onClick={()=>{setDetails(p);setDetailQuery('');}}>{p.name}<span className="block mt-1 text-xs text-muted-foreground font-normal line-clamp-2">{p.description}</span></button>},{key:'currency',label:'Currency',sortValue:p=>p.currency,cell:p=><span className="rounded border px-2 py-1 text-xs font-medium">{p.currency}</span>},{key:'status',label:'Status',cell:p=><StatusBadge status={p.is_active?'active':'archived'}/>},{key:'products',label:'Products priced',align:'right',sortValue:p=>priced(p.id).length,cell:p=>priced(p.id).length},{key:'updated',label:'Latest price update',sortValue:p=>updated(p.id),cell:p=><span className="text-muted-foreground whitespace-nowrap">{updated(p.id)?formatDate(updated(p.id)):'No prices yet'}</span>},{key:'actions',label:'Actions',align:'right',cell:p=><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`Actions for ${p.name}`}><MoreHorizontal className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>{setDetails(p);setDetailQuery('');}}>View prices</DropdownMenuItem><DropdownMenuItem onSelect={()=>edit(p)}>Edit price list</DropdownMenuItem><DropdownMenuItem onSelect={()=>{if(p.is_active)setArchive(p);else void db.updatePriceList(p.id,{...p,is_active:true}).then(reload).then(()=>toast.success('Price list restored'));}}>{p.is_active?'Archive':'Restore'} price list</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}];
 const detailRows=React.useMemo(()=>details?data.products.filter(p=>p.prices?.some(price=>price.price_list_id===details.id)&&`${p.name} ${p.sku}`.toLowerCase().includes(detailQuery.toLowerCase())):[],[details,data,detailQuery]);
 const priceColumns:DataColumn<Product>[]=[{key:'name',label:'Product',sortValue:p=>p.name,cell:p=><div className="max-w-sm"><p className="line-clamp-2 font-medium">{p.name}</p><p className="text-xs text-muted-foreground mt-1">{p.sku}</p></div>},{key:'price',label:'Master price',align:'right',sortValue:p=>p.prices!.find(v=>v.price_list_id===details?.id)!.unit_price,cell:p=>formatCurrency(p.prices!.find(v=>v.price_list_id===details?.id)!.unit_price,details?.currency)},{key:'updated',label:'Updated',cell:p=>formatDate(p.prices!.find(v=>v.price_list_id===details?.id)!.updated_at)},{key:'edit',label:'Actions',align:'right',cell:p=><Button variant="outline" size="sm" disabled={!details?.is_active||!p.is_active} onClick={()=>setPriceProduct(p)}>Edit prices</Button>}];
 return <div className="space-y-5"><PageHeader eyebrow="Product catalog" title="Price Lists" description="Choose a pricing schedule, review coverage, and keep master prices current." actions={<Button onClick={()=>edit(null)}><Plus className="mr-2 h-4 w-4"/>Add Price List</Button>}/><InlineError message={error} onRetry={reload}/><div className="surface"><div className="table-toolbar"><SearchInput value={query} onValueChange={setQuery} placeholder="Search price lists…" className="sm:max-w-sm"/><select aria-label="Filter price list status" className="select-control sm:w-40" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="archived">Archived</option></select></div><DataTable label="price lists" data={rows} columns={columns} rowKey={p=>p.id} loading={loading} emptyTitle="No price lists found" emptyDescription="Create a pricing schedule or adjust your filters."/></div>
 <Dialog open={open} onOpenChange={v=>!saving&&setOpen(v)}><DialogContent><DialogHeader><DialogTitle>{editing?'Edit Price List':'Add Price List'}</DialogTitle><DialogDescription>Each schedule uses a single currency.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4"><InlineError message={formError}/><FormField label="Price list name *"><Input required disabled={saving} value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></FormField><FormField label="Currency *" hint={editing&&priced(editing.id).length?'Currency cannot change once products are priced. Create a new list instead.':undefined}><select disabled={saving||!!(editing&&priced(editing.id).length)} className="select-control" value={form.currency} onChange={e=>setForm(f=>({...f,currency:e.target.value}))}>{['INR','USD','EUR','GBP','AED'].map(c=><option key={c}>{c}</option>)}</select></FormField><FormField label="Description"><Textarea rows={3} disabled={saving} value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></FormField><DialogFooter><Button type="button" variant="outline" disabled={saving} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving}>{saving?'Saving…':'Save Price List'}</Button></DialogFooter></form></DialogContent></Dialog>
 <Dialog open={!!details} onOpenChange={v=>!v&&setDetails(null)}><DialogContent className="sm:max-w-4xl"><DialogHeader><DialogTitle>{details?.name}</DialogTitle><DialogDescription>{details?.currency} · {details?priced(details.id).length:0} products priced. Master changes never alter saved quotations.</DialogDescription></DialogHeader><SearchInput value={detailQuery} onValueChange={setDetailQuery} placeholder="Search products in this list…"/><DataTable label="priced products" data={detailRows} columns={priceColumns} rowKey={p=>p.id} initialPageSize={10} emptyTitle="No priced products" emptyDescription="Add prices in Products or import a spreadsheet."/></DialogContent></Dialog>
 {priceProduct&&<PriceMatrixModal open onOpenChange={v=>!v&&setPriceProduct(null)} product={priceProduct} onEdited={()=>void reload()}/>}<ConfirmationDialog open={!!archive} onOpenChange={v=>!v&&setArchive(null)} title="Archive price list?" description={`${archive?.name} will no longer be available for new quotations. Saved quotations and price history remain unchanged.`} confirmLabel="Archive Price List" onConfirm={async()=>{if(archive){await db.deletePriceList(archive.id);await reload();toast.success('Price list archived');}}}/></div>;
}
