"use client";
import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {usePathname} from 'next/navigation';
import {PanelLeftClose,PanelLeftOpen} from 'lucide-react';
import {cn} from '@/lib/utils';
import {db} from '@/lib/db';
import {Button} from '@/components/ui/button';
import {Tooltip,TooltipContent,TooltipProvider,TooltipTrigger} from '@/components/ui/tooltip';
import {UserNav} from './user-nav';
import {navigation,catalogNavigation,navIsActive} from './navigation';
export function Sidebar({collapsed,onToggle,onNavigate,mobile=false}:{collapsed:boolean;onToggle:()=>void;onNavigate?:()=>void;mobile?:boolean}){
 const pathname=usePathname(),user=db.getCurrentUser(),admin=user?.role==='admin';
 return <TooltipProvider delayDuration={150}><aside aria-label="Main navigation" className={cn('flex h-full shrink-0 flex-col border-r border-slate-200 bg-slate-50/80',mobile?'w-full':collapsed?'w-[72px]':'w-[248px]')}>
 <Link href="/dashboard" onClick={onNavigate} aria-label="Globetrek dashboard" className={cn('flex h-[84px] shrink-0 items-center border-b border-slate-200/80',collapsed?'justify-center':'px-5')}><span className="flex min-w-0 flex-col gap-1.5"><Image src="/brand/globetrek-new-logo.png" alt="GlobeTrek Engineering Corporation" width={817} height={306} className={cn('h-auto shrink-0 object-contain',collapsed?'w-10':'w-[136px]')} priority/>{!collapsed&&<span className="text-[10px] font-medium tracking-[0.04em] text-slate-500">QUOTATION WORKSPACE</span>}</span></Link>
 <div className="flex-1 space-y-6 overflow-y-auto px-3 pb-5 pt-5">{['Workspace','Catalog & customers','Administration'].map(section=>{const entries=navigation.filter(n=>n.section===section&&(!n.adminOnly||admin));return entries.length?<div key={section}>{!collapsed&&<p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.09em] text-slate-500">{section}</p>}<nav aria-label={section} className="space-y-0.5">{entries.map(item=>{const active=navIsActive(pathname,item.href),Icon=item.icon;const link=<Link href={item.href} aria-label={item.title} aria-current={active?'page':undefined} onClick={onNavigate} className={cn('group relative flex min-h-10 items-center gap-2.5 rounded-lg text-[13px] transition-colors',collapsed?'justify-center':'px-3 py-2',active?'bg-white font-semibold text-blue-700 shadow-[0_1px_3px_rgba(15,23,42,0.05)] ring-1 ring-inset ring-slate-200':'text-slate-600 hover:bg-slate-200/50 hover:text-slate-950')}><span className={cn('flex size-5 shrink-0 items-center justify-center transition-colors',active?'text-blue-600':'text-slate-500 group-hover:text-slate-700')}><Icon className="size-[17px]"/></span>{!collapsed&&<span className="min-w-0"><span className="block font-medium leading-5">{item.title}</span></span>}{active&&<span aria-hidden className="absolute inset-y-3 left-0 w-0.5 rounded-full bg-primary"/>}</Link>;return <React.Fragment key={item.href}>{collapsed?<Tooltip><TooltipTrigger asChild>{link}</TooltipTrigger><TooltipContent side="right"><p className="font-medium">{item.title}</p><p className="text-xs opacity-70">{item.description}</p></TooltipContent></Tooltip>:link}{item.href==='/products'&&admin&&pathname.startsWith('/products')&&!collapsed&&<div className="ml-[21px] my-1.5 space-y-0.5 border-l border-slate-200 pl-3">{catalogNavigation.map(sub=><Link key={sub.href} href={sub.href} onClick={onNavigate} aria-current={pathname===sub.href?'page':undefined} className={cn('flex min-h-9 items-center rounded-md px-2.5 py-2 text-xs',pathname===sub.href?'bg-blue-50 font-semibold text-primary':'text-muted-foreground hover:bg-white hover:text-foreground')}>{sub.title}</Link>)}</div>}</React.Fragment>;})}</nav></div>:null;})}</div>
 {!mobile&&<div className="px-3 pb-3"><Button variant="ghost" aria-expanded={!collapsed} aria-label={collapsed?'Expand sidebar':'Collapse sidebar'} onClick={onToggle} className={cn('h-9 w-full text-slate-500 hover:text-slate-800',!collapsed&&'justify-start px-3')}>{collapsed?<PanelLeftOpen/>:<><PanelLeftClose/><span className="text-xs">Collapse sidebar</span></>}</Button></div>}
 <div className={cn('border-t border-slate-200 p-3',collapsed&&'px-2')}><UserNav expanded={!collapsed}/></div>
 </aside></TooltipProvider>;
}
