"use client";
import React from 'react';
import { Plus,UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import { PageHeader,SearchInput,InlineError,FormField,StatusBadge,ConfirmationDialog } from '@/components/workspace/primitives';
import { DataTable,DataColumn } from '@/components/workspace/data-table';
import { useAsyncData } from '@/lib/ui-hooks';
import { db } from '@/lib/db';
import { UserProfile } from '@/types';
import { toast } from 'sonner';
export default function UsersPage(){
 const {data,loading,error,reload}=useAsyncData(()=>db.fetchUsers(),[] as UserProfile[]);const current=db.getCurrentUser();
 const [query,setQuery]=React.useState('');const [roleFilter,setRoleFilter]=React.useState('all');const [open,setOpen]=React.useState(false);const [deleting,setDeleting]=React.useState<UserProfile|null>(null);const [saving,setSaving]=React.useState(false);const [formError,setFormError]=React.useState('');const [form,setForm]=React.useState({full_name:'',email:'',password:'',role:'team_member' as 'admin'|'team_member'});
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setFormError('');try{await db.createUser({...form,full_name:form.full_name.trim(),email:form.email.trim()});await reload();setOpen(false);setForm({full_name:'',email:'',password:'',role:'team_member'});toast.success('User account created');}catch(e){setFormError(e instanceof Error?e.message:'Could not create user.');}finally{setSaving(false);}}
 const rows=React.useMemo(()=>data.filter(u=>(roleFilter==='all'||u.role===roleFilter)&&`${u.full_name} ${u.email}`.toLowerCase().includes(query.toLowerCase())),[data,query,roleFilter]);
 const columns:DataColumn<UserProfile>[]=[{key:'name',label:'Name',sortValue:u=>u.full_name,cell:u=><div className="flex items-center gap-3"><div className="h-8 w-8 rounded-full bg-muted grid place-items-center"><UserRound className="h-4 w-4 text-muted-foreground"/></div><span className="font-medium">{u.full_name}{u.id===current?.id&&<span className="ml-2 text-xs font-normal text-muted-foreground">You</span>}</span></div>},{key:'email',label:'Email',sortValue:u=>u.email,cell:u=><span className="text-muted-foreground">{u.email}</span>},{key:'role',label:'Role',sortValue:u=>u.role,cell:u=>u.role==='admin'?'Administrator':'Team member'},{key:'status',label:'Status',cell:()=><StatusBadge status="active"/>},{key:'actions',label:'Actions',align:'right',cell:u=><Button variant="ghost" size="sm" disabled={u.id===current?.id} onClick={()=>setDeleting(u)}>Deactivate</Button>}];
 return <div className="space-y-5"><PageHeader eyebrow="Administration" title="Users & Permissions" description="Give your team the right access to the shared quotation workspace." actions={<Button onClick={()=>{setFormError('');setOpen(true);}}><Plus className="mr-2 h-4 w-4"/>Add User</Button>}/><InlineError message={error} onRetry={reload}/><div className="surface"><div className="table-toolbar"><SearchInput value={query} onValueChange={setQuery} placeholder="Search name or email…" className="sm:max-w-sm"/><select aria-label="Filter user role" className="select-control sm:w-44" value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="all">All roles</option><option value="admin">Administrators</option><option value="team_member">Team members</option></select></div><DataTable label="users" data={rows} columns={columns} rowKey={u=>u.id} loading={loading} emptyTitle="No users found" emptyDescription="Adjust your search or add a team member."/></div><div className="grid gap-4 sm:grid-cols-2 text-xs text-muted-foreground"><p><strong className="text-foreground font-medium">Team members</strong><br/>Prepare quotations, manage customers, and view the shared product catalog.</p><p><strong className="text-foreground font-medium">Administrators</strong><br/>Also manage products, pricing, imports, users, and company settings.</p></div>
 <Dialog open={open} onOpenChange={v=>!saving&&setOpen(v)}><DialogContent><DialogHeader><DialogTitle>Add User</DialogTitle><DialogDescription>Create a sign-in account for a member of your team.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4"><InlineError message={formError}/><fieldset disabled={saving} className="space-y-4"><FormField label="Full name *"><Input required value={form.full_name} onChange={e=>setForm(f=>({...f,full_name:e.target.value}))}/></FormField><FormField label="Work email *"><Input type="email" required autoComplete="off" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/></FormField><FormField label="Role"><select className="select-control" value={form.role} onChange={e=>setForm(f=>({...f,role:e.target.value as typeof form.role}))}><option value="team_member">Team member</option><option value="admin">Administrator</option></select></FormField><FormField label="Initial password *" hint="Use 12–72 characters. Share the password securely with this user."><Input type="password" required minLength={12} maxLength={72} autoComplete="new-password" value={form.password} onChange={e=>setForm(f=>({...f,password:e.target.value}))}/></FormField></fieldset><DialogFooter><Button type="button" variant="outline" disabled={saving} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving}>{saving?'Creating…':'Create Account'}</Button></DialogFooter></form></DialogContent></Dialog><ConfirmationDialog open={!!deleting} onOpenChange={v=>!v&&setDeleting(null)} title="Deactivate user?" description={`${deleting?.full_name} will lose access and active sessions will end. Existing quotations are preserved.`} confirmLabel="Deactivate User" onConfirm={async()=>{if(deleting){await db.deleteUser(deleting.id);await reload();toast.success('User deactivated');}}}/></div>;
}
