"use client";
import React from 'react';
import Link from 'next/link';
import {ArrowRight,FilePlus2,FileText,Package,Users,Upload,CalendarDays} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {PageHeader,StatCard,SectionHeader,SearchInput,StatusBadge,InlineError} from '@/components/workspace/primitives';
import {DataTable,DataColumn} from '@/components/workspace/data-table';
import {useAsyncData} from '@/lib/ui-hooks';
import {db} from '@/lib/db';
import {formatCurrency,formatDate} from '@/lib/utils';
import {businessDate} from '@/lib/business-date';
import {Quotation,Product,Customer} from '@/types';
export default function DashboardPage(){
 const {data,loading,error,reload}=useAsyncData(async()=>{const [quotes,products,customers]=await Promise.all([db.fetchQuotations(),db.fetchProducts(),db.fetchCustomers()]);return {quotes,products,customers};},{quotes:[] as Quotation[],products:[] as Product[],customers:[] as Customer[]});
 const [query,setQuery]=React.useState(''),admin=db.getCurrentUser()?.role==='admin',month=businessDate().slice(0,7);
 const recent=React.useMemo(()=>data.quotes.filter(q=>[q.quotation_number,q.customer_name].some(v=>v.toLowerCase().includes(query.toLowerCase()))).slice(0,6),[data.quotes,query]);
 const columns:DataColumn<Quotation>[]=[{key:'number',label:'Quotation',cell:q=><Link className="whitespace-nowrap font-medium text-primary hover:underline" href={`/quotations/${q.id}`}>{q.quotation_number}</Link>},{key:'customer',label:'Customer',cell:q=><div><p className="font-medium">{q.customer_name}</p><p className="mt-0.5 text-xs text-muted-foreground">{q.customer_country||'Country not supplied'}</p></div>},{key:'date',label:'Date',cell:q=><span className="whitespace-nowrap text-muted-foreground">{formatDate(q.quotation_date)}</span>},{key:'status',label:'Status',cell:q=><StatusBadge status={q.status}/>},{key:'total',label:'Total',align:'right',cell:q=><span className="whitespace-nowrap font-semibold">{formatCurrency(q.total_amount,q.currency)}</span>}];
 const quick=[{title:'Create quotation',description:'Start a new proposal',href:'/quotations/new',icon:FilePlus2},{title:admin?'Add product':'View products',description:'Open the product catalog',href:admin?'/products?create=1':'/products',icon:Package},{title:'Add customer',description:'Save a customer contact',href:'/customers?create=1',icon:Users},...(admin?[{title:'Import prices',description:'Review an Excel price list',href:'/products/import',icon:Upload}]:[])];
 return <div className="space-y-7"><PageHeader eyebrow="Workspace overview" title="Dashboard" description="A clear view of your catalog, customers and quotation activity." actions={<Button asChild><Link href="/quotations/new"><FilePlus2/>Create Quotation</Link></Button>}/><InlineError message={error} onRetry={reload}/><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatCard label="Quotations this month" value={data.quotes.filter(q=>q.quotation_date.startsWith(month)).length} description={new Date().toLocaleDateString('en-IN',{month:'long',year:'numeric',timeZone:'Asia/Kolkata'})} icon={CalendarDays} loading={loading}/><StatCard label="Total quotations" value={data.quotes.length} description="All saved quotations" icon={FileText} loading={loading}/><StatCard label="Total products" value={data.products.length} description="Your shared product catalog" icon={Package} loading={loading}/><StatCard label="Total customers" value={data.customers.length} description="Across your entire team" icon={Users} loading={loading}/></div><div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold">Recent quotations</h2><p className="mt-1 text-xs text-muted-foreground">Your six most recent matching quotations.</p></div><Button asChild variant="ghost" size="sm"><Link href="/quotations">View history<ArrowRight/></Link></Button></div><SearchInput className="max-w-sm" placeholder="Search recent quotations…" value={query} onValueChange={setQuery}/><DataTable label="Recent quotations" data={recent} columns={columns} rowKey={q=>q.id} loading={loading} emptyTitle={query?'No matching quotations':'Your first quotation starts here'} emptyDescription={query?'Try another customer or quotation number.':'Choose a customer, add products from your price list and create a quotation.'} emptyAction={!query&&<Button asChild><Link href="/quotations/new"><FilePlus2/>Create Quotation</Link></Button>}/></div><div className="space-y-4"><SectionHeader title="Quick actions" description="Pick up a task without the extra clicks."/><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{quick.map(a=><Link key={a.href} href={a.href} className="surface group flex items-start gap-3 p-4 transition-colors hover:border-slate-300 hover:bg-slate-50"><a.icon className="mt-0.5 size-4 text-muted-foreground"/><div className="min-w-0 flex-1"><p className="text-[13px] font-medium">{a.title}</p><p className="mt-1 text-xs text-muted-foreground">{a.description}</p></div><ArrowRight className="mt-0.5 size-3.5 text-muted-foreground group-hover:text-primary"/></Link>)}</div></div></div>;
}
